//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtacFeed.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://romamobilita.it/sites/default/files/rome_rtgtfs_vehicle_positions_feed.pb" +
            "")]
        public string UrlVehicle {
            get {
                return ((string)(this["UrlVehicle"]));
            }
            set {
                this["UrlVehicle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://romamobilita.it/sites/default/files/rome_rtgtfs_trip_updates_feed.pb")]
        public string UrlTrip {
            get {
                return ((string)(this["UrlTrip"]));
            }
            set {
                this["UrlTrip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int DeltaTSec {
            get {
                return ((int)(this["DeltaTSec"]));
            }
            set {
                this["DeltaTSec"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Duplicati {
            get {
                return ((bool)(this["Duplicati"]));
            }
            set {
                this["Duplicati"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Vuote {
            get {
                return ((bool)(this["Vuote"]));
            }
            set {
                this["Vuote"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SalvaCSV {
            get {
                return ((bool)(this["SalvaCSV"]));
            }
            set {
                this["SalvaCSV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SalvaXlsx {
            get {
                return ((bool)(this["SalvaXlsx"]));
            }
            set {
                this["SalvaXlsx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SalvaGrafico {
            get {
                return ((bool)(this["SalvaGrafico"]));
            }
            set {
                this["SalvaGrafico"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SalvaMonitoraggio {
            get {
                return ((bool)(this["SalvaMonitoraggio"]));
            }
            set {
                this["SalvaMonitoraggio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SalvaAlert {
            get {
                return ((bool)(this["SalvaAlert"]));
            }
            set {
                this["SalvaAlert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("radioNonRaggruppare")]
        public string RadioRaggruppamento {
            get {
                return ((string)(this["RadioRaggruppamento"]));
            }
            set {
                this["RadioRaggruppamento"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://romamobilita.it/sites/default/files/rome_rtgtfs_service_alerts_feed.pb")]
        public string UrlAlert {
            get {
                return ((string)(this["UrlAlert"]));
            }
            set {
                this["UrlAlert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StoricoAlert {
            get {
                return ((bool)(this["StoricoAlert"]));
            }
            set {
                this["StoricoAlert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CheckTrip {
            get {
                return ((bool)(this["CheckTrip"]));
            }
            set {
                this["CheckTrip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://github.com/EnricoTolomei/GTFS_RSM/releases/latest")]
        public string UrlDownload {
            get {
                return ((string)(this["UrlDownload"]));
            }
            set {
                this["UrlDownload"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://github.com/EnricoTolomei/GTFS_RSM")]
        public string UrlHome {
            get {
                return ((string)(this["UrlHome"]));
            }
            set {
                this["UrlHome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool tabGrigliaOld {
            get {
                return ((bool)(this["tabGrigliaOld"]));
            }
            set {
                this["tabGrigliaOld"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExtraSetting {
            get {
                return ((bool)(this["ExtraSetting"]));
            }
            set {
                this["ExtraSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CheckAnomalie {
            get {
                return ((bool)(this["CheckAnomalie"]));
            }
            set {
                this["CheckAnomalie"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CheckSovraffollamento {
            get {
                return ((bool)(this["CheckSovraffollamento"]));
            }
            set {
                this["CheckSovraffollamento"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UrlGTFS_Statico {
            get {
                return ((string)(this["UrlGTFS_Statico"]));
            }
            set {
                this["UrlGTFS_Statico"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UrlMD5_GTFS_Statico {
            get {
                return ((string)(this["UrlMD5_GTFS_Statico"]));
            }
            set {
                this["UrlMD5_GTFS_Statico"] = value;
            }
        }
    }
}
